### PR TITLE
Made it work faster

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by ghost** [comment]
ill merge this commit when the plugin gets accepted :) [ just submitted the plugin before i see this :( ]

**Comment by PEMapModder** [comment]
Tell @humerus about this fix so that he can approve it if he has doubts on what I fixed.

**Comment by ghost** [comment]
i did the same way with VIPSlots with what you suggested. i still need to go with the procedual way where the plugin gets accepted or not, it if it is, ill push the new update and wait till it gets updated.

**Comment by iksaku** [comment]
Why not to make it "node" based? Pocketmine manages user chat interface with the permission nodes:
- `pocketmine.broadcast.user`
- `pocketmine.broadcast.admin`

**Comment by ghost** [comment]
not really the plugin intention xD node base is just like chat mute/unmute for me :P

**Comment by PEMapModder** [comment]
@iksaku because you have to change the permissions every time a player changes level. In terms of efficiency, this is not really a good idea. Also, the permission thing just serves at a convenience method, and it isn't really a large part of the API that we would call it the "base" off PocketMine chat sending. Actually, it is only used to send op-only messages. PocketMine is just another code written in PHP. They are **not** native methods or something like that. Re-implementing a PocketMine API function does **not** make the server slower, but actually one less stack trace. Since looping through the players to check for levels is in fact faster than changing permission every time a player changes the level, and that filtering levels actually spends similar resource to filtering permissions, we should compare them in an equal basis, instead of bias towards "it is an API function".

| item to compare | filter levels every chat | using permissions |
| --: | :-: | :-: |
| when the player changes level | no resources used | PocketMine has to recalculate permissions |
| when the player chats | LevelChat loops through all players and filters out those not in the same level | LevelChat cancels the event and calls the `Server::broadcast()` method, which loops through all players and filters out those not with that permission |
| compatibility with other plugins | handlers of lower priority or the same priority may not be aware of the change in recipient list (however if a plugin wants to check this, they should do it in the MONITOR priority or the HIGHEST priority if they want to modify) | handlers of higher priorities cannot listen to the event, esp. those at the MONITOR priority will never know that the player chatted, and even if they know that this plugin exists, it is less simple to make an API that works with this |

**Comment by PEMapModder** [comment]
^ read the updated comment

**Comment by PEMapModder** [comment]
So as you can see from this table, `Server::broadcast()` is actually similar to, if not slower than, this event handler plus the ultimate function that loops through the recipients list and send to each remaining recipient.

_People who tell you that API methods are faster are most likely talking about Java `native` methods (that are run in C++), Java API functions (that are native to the system) or PHP's API methods (that are also run in C++)._ Because:

``` php
function shift(&$array){
    return array_shift($array);
}
```

is actually the same as

``` php
function shift(&$array){
    $result = $array[array_keys($array)[0]];
    $array = array_slice($array, 1, count($array - 1), true);
    return $result;
}
```

except that PHP has to run user-written code in the second snippet, but run precompiled native assembled C++ code in the first snippet, so the first snippet is faster. This is when using API functions are faster. But if you compare copying the second snippet's contents directly to your code rather than calling the function first, actually they are the same, and possibly copying is faster because there is one less layer of stack trace (although copying requires more code parsing; but this is not the case).

**Comment by ghost** [comment]
@PEMapModder this commit doesnt work as expected. the chat still shows.

**Pull request closed without merging**
